theme: minima
title: "竹嶋亮馬 ポートフォリオ"
description: "機械工学×データ解析の研究者ポートフォリオ"

# ナビゲーションメニュー（手動でリンクを作成）
header_pages:
  - about.md
  - research.md
  - internship.md
  - activities.md
  - contact.md

# Markdownの設定
markdown: kramdown
highlighter: rouge
