# --- サイト情報 ---
title: "竹嶋亮馬 ポートフォリオ"
description: "機械工学×データ解析の研究者ポートフォリオ"
lang: "ja"
url: "https://tamarima.github.io"
baseurl: ""  # 変更不要（プロジェクト名なしの場合）

# --- ナビゲーション ---
nav:
  - title: "ホーム"
    url: "/"
  - title: "自己紹介"
    url: "/about/"
  - title: "研究内容"
    url: "/research/"
  - title: "インターン経験"
    url: "/internship/"
  - title: "課外活動"
    url: "/activities/"
  - title: "お問い合わせ"
    url: "/contact/"

# --- GitHub Pages 設定 ---
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# --- Markdown 設定 ---
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
